dist: xenial
sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - pip install pipenv

install:
  - pipenv install

script:
  - pytest

notifications:
  email: false